logging:
  level:
    org:
      hibernate:
        SQL: DEBUG
        type: TRACE
server:
  error:
    include-exception: true
    include-message: always
    include-stacktrace: always
  port: 9988
spring:
  datasource:
    driver-class-name: org.mariadb.jdbc.Driver
    password: root
    url: jdbc:mariadb://localhost:3306/Tenant?createDatabaseIfNotExist=true
    username: root
  jpa:
    hibernate:   
      ddl-auto: create-drop

    properties:
      hibernate:
        dialect: org.hibernate.dialect.MariaDBDialect
        format_sql: true
    show-sql: true
  security:
    user:
      name: user
      password: password
  ##RabitMQ
  rabbitmq:
    host: "localhost"
    port: 5672
    username: "guest"
    password: "guest"
    template:
      retry:
        enabled: true
        initial-interval: "2s"
        rabbitmq:
  
    exchange: Template
    queue: Template
    routingkey: Template
    virtual-host: /
    vhost: /
    
app:
  message: Message has been sent Successfully..




    
springdoc:
  swagger-ui:
    path: /swagger-ui.html
    

